version: "3"
services: 

  api:
    build: 
      context: .
      dockerfile: ./build/calculator/Dockerfile
    image: ${REGISTRY_IMAGE_API}:${GIT_COMMIT_SHORT}-jenkins-${CURRENT_BUILD_NUMBER}
    networks:
      - dmz_ssl
    environment:
      - VIRTUAL_HOST=calculator.qwerty.com.ar
      - LETSENCRYPT_HOST=calculator.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com
      - VIRTUAL_PORT=5000

networks:
  dmz_ssl:
    external: true
