version: "3"
services: 

  documentation:
    build: 
      context: .
      dockerfile: ./build/documentation/Dockerfile
    image: joagonzalez/calculator-doc:0.0.1
    networks:
      - dmz  
    environment:
      - VIRTUAL_HOST=doc.calculator.qwerty.com.ar
      - LETSENCRYPT_HOST=doc.calculator.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com

networks:
  dmz:
    external: true
