version: "3"
services: 

  api:
    build: 
      context: .
      dockerfile: ./build/calculator/Dockerfile
    image: ${REGISTRY_IMAGE_API}:${API_VERSION}
    networks:
      - dmz_ssl
    # ports:
    #   - "5001:5000"
    environment:
      - VIRTUAL_HOST=calculator.qwerty.com.ar
      - LETSENCRYPT_HOST=calculator.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com
      - VIRTUAL_PORT=5000
      - API_VERSION=${API_VERSION}

networks:
  dmz_ssl:
    external: true
