version: "3"
services: 

  documentation:
    build: 
      context: .
      dockerfile: ./build/Dockerfile_documentation
    image: joagonzalez/calculator-doc:0.0.1
    ports:
      - "80:80"
    networks:
      - dmz  
    environment:
      - VIRTUAL_HOST=doc.calculator.qwerty.com.ar
      - LETSENCRYPT_HOST=doc.calculator.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com

networks:
  dmz:
    external: true

volumes:
  db_data: