site_name: Calculator App
site_url: https://calculator.qwerty.com.ar

nav:
  - Calculator: 
    - Overview: index.md
    - Application: calculator.md
    - Endpoints: endpoints.md
    - Services: services.md
  - Tests: tests.md

theme:
  name: readthedocs

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true