site_name: Calculator App
site_url: https://calculator.qwerty.com.ar
repo_url: https://github.com/joagonzalez/python-seed/
edit_uri: edit/master/docs/

nav:
  - Calculator: 
    - Overview: index.md
    - Application: calculator.md
    - Endpoints: endpoints.md
    - Services: services.md
  - Tests: tests.md

theme:
  name: readthedocs
  features:
    - content.action.edit
    - content.action.view
    
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true

extra_css:
  - css/extra.css